WebTechIT/WebTechIT/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),

]

WebTechIT/home/urls.py
from home.views import index
from django.conf.urls import url
from home.views import\
     (
     index,
     post_detail_view,
     login_view,
     logout_view,
     register_user_view,
     add_comment,
     about_view
)
app_name = 'home'

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^home/(?P<slug>[\w-]+)/$', post_detail_view, name='post-detail'),
     url(r'^home/(?P<slug>[\w-]+)/comments/$', add_comment, name='new-comment'),
     url(r'^login/$', login_view, name='login'),
     url(r'^logout/$', logout_view, name='logout'),
     url(r'^register/$', register_user_view, name='register'),
     url(r'^about/$', about_view, name='about')
]

WebTechIT/home/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from .utils import unique_slug_generator

class BaseHome(models.Model):
    Create_date = models.DateTimeField(auto_now_add=True)
    Update_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class DanhMuc(models.Model):
    Name         = models.CharField(max_length=255)
    Is_Status    = models.BooleanField(default=True)

    def __str__(self):
        return "%d %s" % (self.pk, self.Name)

class LoaiTin(models.Model):
    Title       = models.CharField(max_length=255, null= True)
    idDanhMuc   = models.ForeignKey(DanhMuc)

    def __str__(self):
        return (self.Title)

class Category(models.Model):
    name    = models.CharField(max_length=128, unique=True)
    views   = models.IntegerField(default=0)
    likes   = models.IntegerField(default=0)
    slug    = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class TinTuc(BaseHome):
    Title           = models.CharField(max_length=500,null=True)
    slug            = models.SlugField(null=True, blank=True)
    Id_DanhMuc      = models.ForeignKey(DanhMuc)
    Id_LoaiTin      = models.ForeignKey(LoaiTin, null=True)
    category        = models.ForeignKey(Category, null=True)
    Decriptions     = models.CharField(max_length=255, null=True, blank=True)
    Content         = RichTextField(verbose_name='Noi dung', null=True, blank=True)
    Image           = models.FileField(upload_to='images', null=True, blank=True)
    Views           = models.IntegerField(default=0)
    Creator         = models.ForeignKey(User, null=True)
    Is_HightLight   = models.BooleanField(default=False)

    def __str__(self):
        return str(self.Title)

    @property
    def title(self):
         return (self.Title)

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(rl_pre_save_receiver, sender=TinTuc)



class HashTag(models.Model):
    Name        = models.CharField(max_length=255)
    Is_Status   = models.BooleanField(default=True)

    def __str__(self):
        return (self.pk, self.Name)

class TTHagTag(models.Model):
    Id_HashTag   = models.ForeignKey(HashTag)
    Is_Status    = models.BooleanField(default=True)

class Images(BaseHome):
    Name            = models.CharField(max_length=255)
    Image           = models.FileField(upload_to='images', null=True)
    alt             = models.CharField(max_length=50, null=True)
    Is_Allowlink    = models.BooleanField(default=True)

    def __str__(self):
        return (self.Name)

class Photographer(models.Model):
    Name        = models.CharField(max_length=255)
    Is_Display  = models.BooleanField(default=True)



class Comment(BaseHome):
    user        = models.ForeignKey(User)
    post        = models.ForeignKey(TinTuc)
    content     = models.TextField(verbose_name='Nội Dung')
    def __str__(self):
        return "%s %s" % (self.pk, self.content)

WebTechIT/home/forms.py
from django import forms
import itertools
from django.utils.text import slugify
from django.forms import ModelForm, PasswordInput
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
User = get_user_model()
from home.models import Comment, TinTuc

#class LoginForm(ModelForm):
#    class Meta:
#       model = User
#        fields = ("username", "password")

#        widgets ={
#           "password": PasswordInput()
#        }
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if username and password:
            user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("This user does not exits")
        if not user.check_password(password):
            raise forms.ValidationError("Incorrect password")
        if not user.is_active:
            raise forms.ValidationError("This user is not longer avtive")
        return super(LoginForm, self).clean(*args, **kwargs)


class RegisterForm(ModelForm):
    first_name = forms.CharField(label='Firts Name')
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    confirm_password = forms.CharField(max_length=20, widget=PasswordInput())

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username", "password")
        widgets = {
            "password": PasswordInput()
        }

    # Ghi đè phương thức kiểm tra input
    def clean(self):
        clean_data = super().clean()
        password = clean_data.get("password")
        confirm_password = clean_data.get("confirm_password")
        if not confirm_password == password:
            self.add_error("password", "Passwords are not match.")

    def save(self):
        user = super().save()
        user.set_password(self.cleaned_data["password"])
        user.save()

        return user


class CommnentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

    def __init__(self, *args, **kwargs):
        self.post = kwargs.pop("post", "")
        self.current_user = kwargs.pop("user", "")

        super(). __init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.user = self.current_user
        self.instance.home = self.home

        return super().save(commit=commit)

WebTechIT/home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.http import HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.http import  Http404
from django.urls import reverse
from django.utils.text import slugify

from .forms import  LoginForm, CommnentForm, RegisterForm
from django.shortcuts import render, get_object_or_404, redirect

from .models import DanhMuc, TinTuc, HashTag, Category, LoaiTin, Images, Comment

def index(request):
    posts = TinTuc.objects.all().order_by("-id")[:5]
    congnghes = TinTuc.objects.all().order_by("-id")[10:]
    tintucs = TinTuc.objects.all().order_by("-id")

    danhmucs = DanhMuc.objects.all()
    context = {
        "danhmucs"      : danhmucs,
        "top_post"      : posts[0],
        "posts"         : posts[1:],
        "tinmois"       : posts,
        "noibats"       : posts,
        "tamsucoder"    : tintucs[:5],
        "tintucs"       : tintucs[:5],
        "moinhats"      : posts,
        "top_congnghe"  : congnghes[0],
        "congnghes"     : congnghes[1:],
        "categories"    : Category.objects.order_by('-likes'),
        "loaitins"      : LoaiTin.objects.all(),
        "images"        : Images.objects.all(),
    }
    return render(request, 'home/index.html',context)


def login_view(request):
    title = "Login"
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username     = form.cleaned_data.get("username")
        password     = form.cleaned_data.get("password")
        user         = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect("/")

    return render(request, "login1.html", {"form": form, "title": title,  "danhmucs": DanhMuc.objects.all(),})


def logout_view(request):
    logout(request)

    return redirect(reverse('home:index'))

def register_user_view(request):
    title = "Register"
    form = RegisterForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()

            return redirect(reverse('home:login'))

    return render(request, "register.html", {"register_form": form })


@login_required #Bắt buộc đăng nhập
def add_comment(request, id):
    if request.method == "POST":
        comment_form = CommnentForm(request.POST, user=request.user, post=TinTuc.objects.get(pk=id))
        if comment_form.is_valid():
            comment_form = comment_form.save(commit=True)
            comment_form.save()
            return redirect(reverse("post-detail", kwargs={"post_id": id}))

    return HttpResponseNotFound()


#@login_required
def post_detail_view(request, slug):
        post = get_object_or_404(TinTuc, slug=slug)
        comment_form = CommnentForm()
        return render(request, 'post/post_detail.html', {
            'tintucs'            : TinTuc.objects.get(slug=slug),
            "danhmucs"           : DanhMuc.objects.all(),
            "tinmois"            : TinTuc.objects.all(),
            "tamsucoder"         : TinTuc.objects.all(),
            'comment_form'       : comment_form,
            "add_comment_action" : reverse("home:new-comment", kwargs={"slug": slug}),

    })

def about_view(request):
    return render(request, 'home/About.html')

WebTechIT/home/templates/base.html
<!DOCTYPE html>
{% load static %}

<head>
   <title> {% block title %} Tech IT {% endblock %} </title>
   
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/li-scroller.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static "images/icon_page.png" %}" />

</head>

<body>

<div id="preloader">
    <div id="status"></div>
</div>
<a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
<div class="container">

   <header id="header">
        <div class="row">
            <!-- Home - Contact - Logo -->
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="header_top">
                    <div class="header_top_left">
                        <ul class="top_nav">
                            {% if request.user.is_authenticated %}
                                <li><a  href="{% url 'home:index' %}"><i class="fa fa-home" aria-hidden="true"></i>&nbsp; Home</a></li>
                                <li><a href="{% url 'home:about' %}">About</a></li>
                                <li><a href="#">Contact</a></li>
                                <li><a href="{% url 'home:about' %}"><i class="fa fa-user" aria-hidden="true"></i>&nbsp; {{ request.user.username }}</a></li>
                                <li><a href="{% url 'home:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Log out</a></li>
                            {% else %}
                                <li><a href="{% url 'home:index' %}"><i class="fa fa-home" aria-hidden="true"></i>&nbsp; Home</a></li>
                                <li><a href="#">About</a></li>
                                <li><a href="#">Contact</a></li>
                                <li><a href="{% url 'home:login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp; Login</a></li>
                                <li><a href="{% url 'home:register' %}"><i class="fa fa-registered" aria-hidden="true"></i>&nbsp; Resgion</a></li>
                            {% endif %}
                        </ul>
                        </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="header_bottom">
                    <div class="logo_area">
                        <a href="{% url 'home:index' %}" class="logo"><img src="{% static 'images/logo.png' %}" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <!--  MENU  -->
  <section id="navArea">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav main_nav">

          <li class="active"><a href="{% url 'home:index' %}"><span class="fa fa-home desktop-home"></span><span class="mobile-show">Home</span></a></li>

            {% for danhmuc in danhmucs %}
                <li><a href="home/{{ danhmuc.slug }}">{{ danhmuc.Name }}</a></li>
            {% endfor %}
        </ul>
      </div>
    </nav>
  </section>

    <!-- TIN MỚI -->
  <section id="newsSection">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="latest_newsarea"> <span>Tin Mới</span>

          <ul id="ticker01" class="news_sticker">
           {% for tinmoi in tinmois %}
                 <li><a href="home/{{ tinmoi.slug }}"><img src="{% static tinmoi.Image %}" alt="">{{ tinmoi.Title }}</a></li>
           {% endfor %}  
          </ul>

        <!-- Facebook -->
          <div class="social_area">
            <ul class="social_nav">
              <li class="facebook"><a href="#"></a></li>
              <li class="twitter"><a href="#"></a></li>
              <li class="flickr"><a href="#"></a></li>
              <li class="pinterest"><a href="#"></a></li>
              <li class="googleplus"><a href="#"></a></li>
              <li class="vimeo"><a href="#"></a></li>
              <li class="youtube"><a href="#"></a></li>
              <li class="mail"><a href="#"></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>

    <!-- SLIDER  -->
  <section id="sliderSection">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
           {% block slick_slider %}
           {% endblock %}
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
           {% block tinnoibat %}
           {% endblock %}
      </div>
    </div>
  </section>

  <section id="contentSection">
    <div class="row">
          <div class="col-lg-8 col-md-8 col-sm-8">
           {% block left_content %}
           {% endblock %}
          </div>

        <!--right-content-->
          <div class="col-lg-4 col-md-4 col-sm-4">
            <aside class="right_content">
                <div class="single_sidebar">
                    <h2><span>TÂM SỰ CODER</span></h2>
                    {% for tinlienquan in tamsucoder %}
                        <ul class="spost_nav">
                            <li>
                                <div class="media wow fadeInDown">
                                    <a href="{{ tinlienquan.slug }}" class="media-left"> <img alt="" src="{% static tinlienquan.Image %}"> </a>
                                    <div class="media-body"> <a href="{{ tinlienquan.slug }}" class="catg_title">{{tinlienquan.Title}}</a> </div>
                                </div>
                            </li>
                        </ul>
                    {% endfor %}
                </div>
              <div class="single_sidebar">
                <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#category" aria-controls="home" role="tab" data-toggle="tab">Category</a></li>
                  <li role="presentation"><a href="#video" aria-controls="profile" role="tab" data-toggle="tab">Video</a></li>
                </ul>
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane active" id="category">
                    <ul>
                        {% for cate in categories %}
                      <li class="cat-item"><a href="#">{{ cate.name }}</a></li>
                        {% endfor %}
                    </ul>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="video">
                    <div class="vide_area">
                      <iframe width="100%" height="250" src="http://www.youtube.com/embed/h5QWbURNEpA?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>
                    </div>
                  </div>

                </div>
              </div>
              <div class="single_sidebar wow fadeInDown">
                <h2><span>Videos</span></h2>
                     <div role="tabpanel" class="tab-pane" id="video">
                    <div class="vide_area">
                      <iframe width="100%" height="250" src="http://www.youtube.com/embed/h5QWbURNEpA?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>
                    </div>
                  </div>

              <div class="single_sidebar wow fadeInDown">
                <h2><span>Link</span></h2>
                <ul>
                  <li><a href="{% url 'home:index' %}">Home </a></li>
                  <li><a href="{% url 'home:index' %}">New</a></li>
                  <li><a href="{% url 'home:login' %}">Login</a></li>
                  <li><a href="{% url 'home:register' %}">Register</a></li>
                </ul>
              </div>
            </aside>
          </div>
    </div>
  </section>

    <!-- Footer -->
  <footer id="footer">
    <div class="footer_top">
      <div class="row">
        <div class="col-lg-6 col-md-4 ">
          <div class="footer_widget wow fadeInDown">
            <h2>Tag</h2>
            <ul class="tag_nav">
                {% for danhmuc in danhmucs %}
                     <li><a href="#">{{ danhmuc.Name }}</a></li>
                {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-lg-6 col-md-4 ">
          <div class="footer_widget wow fadeInRightBig">
            <h2>Contact</h2>
              <p> <h4>TRƯƠNG MINH PHONG </h4>
                  HCMC OPEN UNIVERSITY<br>
                  PHONE: 0127 679 4575<br>
                  Program: Python - Django.
              </p>
              <r/>
            <address>
            785/10 Nguyễn Kiệm, Phường 13, Quận Tân Bình ,VN Phone: (+84) 127 679 4575 | Mail: 1451010130phong@ou.edu.com
            </address>
          </div>
        </div>
      </div>
    </div>
    <div class="footer_bottom">
      <p class="copyright">Copyright &copy; 2045 <a href="home/index.html">WechTechIT</a></p>
      <p class="developer">Developed By PhongTruong</p>
    </div>
  </footer>
</div>
<!--Like-share -->
     <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.10&appId=1691790350834242';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<!--------end Like-share ------->

<!---Comment---->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.10&appId=1691790350834242';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<!---End comment -->



    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.li-scroller.1.0.js' %}"></script>
    <script src="{% static 'js/jquery.newsTicker.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

WebTechIT/home/templates/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}
{% block left_content %}
   <div class="col-sm-6 col-sm-offset-3">
     <h1>{{ title }}</h1>
   <hr/>

       <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
           {{ form }}
           <input type="submit" class="btn btn-theme" value='{{ title }}' />

       </form>
         <div class="panel-footer">
             Don't have an account? <a href="{% url 'home:register' %}"><font color="#ff4500">Click here</font>  </a> to register.
        </div>
        <div class="fb-login-button" data-max-rows="1" data-size="medium" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
   </div>
{% endblock %}

WebTechIT/home/templates/login1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
     <link rel="shortcut icon" href="{% static "images/icon_page.png" %}" />
    <title>Login</title>
</head>
<body>
    <div class="body"></div>
    <div class="grad"></div>
    <div class="header">
        <div>WebTech<span>IT</span></div>
    </div>
		<br>
		<div class="login">
			 <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
                 <table>
                     {{ form }}
                 </table>
                 <div class="panel-body">
                 Don't have an account? <a href="{% url 'home:register' %}"><font color="#ff4500">Click here</font>  </a> to register.
             </div>
                 <input type="submit" class="btn btn-theme" value='{{ title }}'>
                 <div class="fb-login-button" data-max-rows="1" data-size="medium" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
             </form>

		</div>

<!--Login-face -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.10&appId=1691790350834242';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<!--end Login -->
</body>
</html>

WebTechIT/home/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
     <link rel="shortcut icon" href="{% static "images/icon_page.png" %}" />
    <title>Login</title>
</head>
<body>
    <div class="body"></div>
    <div class="grad"></div>
    <div class="header">
        <div>Resgis<span>ter</span></div>
    </div>
		<br>
        <div class="login">
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                {{ register_form }}
                <tr>
                    <td><input type="submit" class="btn btn-theme" value="Đăng ký" /></td>
                </tr>
            </table>
        </form>
    </div>
</body>
</html>